// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-mma-quant-q4_1.cuh"
#ifdef GGML_CUDA_FA_ALL_QUANTS
#include "../fattn-mma-quant-loaders.cuh"
#endif // GGML_CUDA_FA_ALL_QUANTS
#include "../fattn-mma-f16.cuh"

#ifdef GGML_CUDA_FA_ALL_QUANTS
DECL_FATTN_MMA_QUANT_CASE(GGML_TYPE_Q4_1, 64, 64, 8, 8);
DECL_FATTN_MMA_QUANT_CASE(GGML_TYPE_Q4_1, 128, 128, 8, 8);
DECL_FATTN_MMA_QUANT_CASE(GGML_TYPE_Q4_1, 256, 256, 8, 8);
#endif // GGML_CUDA_FA_ALL_QUANTS
