// Quantized-native Q8_0/Q8_0 MMA FlashAttention instances.
// Hand-written rather than generated by generate_cu_files.py: only the
// (ncols1, ncols2) pairs reachable for Q8_0/Q8_0 are instantiated.

#include "../fattn-mma-q8-case.cuh"

DECL_FATTN_MMA_Q8_CASE(64, 64, 1, 8);
DECL_FATTN_MMA_Q8_CASE(64, 64, 2, 8);
DECL_FATTN_MMA_Q8_CASE(64, 64, 4, 8);
DECL_FATTN_MMA_Q8_CASE(64, 64, 8, 8);

DECL_FATTN_MMA_Q8_CASE(128, 128, 1, 8);
DECL_FATTN_MMA_Q8_CASE(128, 128, 2, 8);
DECL_FATTN_MMA_Q8_CASE(128, 128, 4, 8);
DECL_FATTN_MMA_Q8_CASE(128, 128, 8, 8);

DECL_FATTN_MMA_Q8_CASE(256, 256, 1, 8);
DECL_FATTN_MMA_Q8_CASE(256, 256, 2, 8);
DECL_FATTN_MMA_Q8_CASE(256, 256, 4, 8);
DECL_FATTN_MMA_Q8_CASE(256, 256, 8, 8);
