// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-mma-f16.cuh"

#ifdef GGML_CUDA_FA_ALL_QUANTS
DECL_FATTN_MMA_QUANT_CASE(GGML_TYPE_Q6_1, 64, 64, 1, 8);
DECL_FATTN_MMA_QUANT_CASE(GGML_TYPE_Q6_1, 128, 128, 1, 8);
DECL_FATTN_MMA_QUANT_CASE(GGML_TYPE_Q6_1, 256, 256, 1, 8);
#endif // GGML_CUDA_FA_ALL_QUANTS
