// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-mma-quant-q5_0.cuh"
#ifdef GGML_CUDA_FA_ALL_QUANTS
#include "../fattn-mma-quant-loaders.cuh"
#endif // GGML_CUDA_FA_ALL_QUANTS
#include "../fattn-mma-f16.cuh"

#ifdef GGML_CUDA_FA_ALL_QUANTS
DECL_FATTN_MMA_QUANT_CASE(GGML_TYPE_Q5_0, 64, 64, 8, 4);
DECL_FATTN_MMA_QUANT_CASE(GGML_TYPE_Q5_0, 128, 128, 8, 4);
DECL_FATTN_MMA_QUANT_CASE(GGML_TYPE_Q5_0, 256, 256, 8, 4);
#endif // GGML_CUDA_FA_ALL_QUANTS
