// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-mma-f16.cuh"

#ifdef GGML_CUDA_FA_ALL_QUANTS
DECL_FATTN_MMA_QUANT_CASE(GGML_TYPE_Q3_0, 64, 64, 4, 4);
DECL_FATTN_MMA_QUANT_CASE(GGML_TYPE_Q3_0, 128, 128, 4, 4);
DECL_FATTN_MMA_QUANT_CASE(GGML_TYPE_Q3_0, 256, 256, 4, 4);
#endif // GGML_CUDA_FA_ALL_QUANTS
