// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-mma-f16.cuh"

DECL_FATTN_MMA_QUANT_CASE(GGML_TYPE_Q5_0, 64, 64, 4, 8);
DECL_FATTN_MMA_QUANT_CASE(GGML_TYPE_Q5_0, 128, 128, 4, 8);
DECL_FATTN_MMA_QUANT_CASE(GGML_TYPE_Q5_0, 256, 256, 4, 8);
