// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-mma-quant-q4_0.cuh"
#ifdef GGML_CUDA_FA_ALL_QUANTS
#include "../fattn-mma-quant-loaders.cuh"
#endif // GGML_CUDA_FA_ALL_QUANTS
#include "../fattn-mma-f16.cuh"

DECL_FATTN_MMA_QUANT_CASE(GGML_TYPE_Q4_0, 64, 64, 2, 8);
DECL_FATTN_MMA_QUANT_CASE(GGML_TYPE_Q4_0, 128, 128, 2, 8);
DECL_FATTN_MMA_QUANT_CASE(GGML_TYPE_Q4_0, 256, 256, 2, 8);
