// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-mma-f16.cuh"

#ifdef GGML_CUDA_FA_ALL_QUANTS
DECL_FATTN_MMA_QUANT_CASE(GGML_TYPE_Q3_1, 64, 64, 2, 4);
DECL_FATTN_MMA_QUANT_CASE(GGML_TYPE_Q3_1, 128, 128, 2, 4);
DECL_FATTN_MMA_QUANT_CASE(GGML_TYPE_Q3_1, 256, 256, 2, 4);
#endif // GGML_CUDA_FA_ALL_QUANTS
