#!/usr/bin/env python3

from glob import glob
import os
import re

HEAD_SIZES_KQ = [40, 64, 72, 80, 96, 112, 128, 192, 256, 320, 512, 576]

# DKQ -> DV override for asymmetric head dims.
HEAD_SIZES_V_OVERRIDE = {576: 512, 320: 256, 192: 128}

TYPES_KV = [
    "GGML_TYPE_F16",
    "GGML_TYPE_BF16",
    "GGML_TYPE_Q8_0",
    "GGML_TYPE_Q6_1",
    "GGML_TYPE_Q6_0",
    "GGML_TYPE_Q5_1",
    "GGML_TYPE_Q5_0",
    "GGML_TYPE_Q4_1",
    "GGML_TYPE_Q4_0",
    "GGML_TYPE_Q3_1",
    "GGML_TYPE_Q3_0",
    "GGML_TYPE_Q2_1",
    "GGML_TYPE_Q2_0S",
]

EXTRA_FATTN_VEC_TYPES = []

SOURCE_FATTN_TILE = """// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-tile.cuh"

DECL_FATTN_TILE_CASE({head_size_kq}, {head_size_v});
"""

SOURCE_FATTN_VEC = """// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE( 64, {type_k}, {type_v});
DECL_FATTN_VEC_CASE(128, {type_k}, {type_v});
DECL_FATTN_VEC_CASE(256, {type_k}, {type_v});
DECL_FATTN_VEC_CASE(512, {type_k}, {type_v});
"""

SOURCE_FATTN_MMA_START = """// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-mma-f16.cuh"

"""

SOURCE_FATTN_MMA_CASE = "DECL_FATTN_MMA_F16_CASE({head_size_kq}, {head_size_v}, {ncols1}, {ncols2});\n"

FATTN_MMA_QUANT_HEAD_SIZES = [64, 128, 256]

FATTN_MMA_QUANT_MANIFEST = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), os.pardir, "fattn-mma-quant-types.h")


def read_fattn_mma_quant_types():
    """Read the native MMA cache-type inventory from its single source.

    fattn-mma-quant-types.h is the one place the type set is written down; the
    route predicate, the extern declarations, the CMake source filter and the
    backend-ops coverage all read it too. Parsing it here rather than keeping a
    copy is what stops a type from being generated but not routable, or the
    reverse.
    """
    entry_re = re.compile(
        r"^\s*ENTRY\(\s*(GGML_TYPE_\w+)\s*,\s*(\w+)\s*,\s*(DEFAULT|EXTRA)\s*,\s*ARGS\s*\)")

    default_types = []
    extra_types   = []
    with open(FATTN_MMA_QUANT_MANIFEST) as manifest:
        for line in manifest:
            match = entry_re.match(line)
            if not match:
                continue
            type_name, stem, tier = match.groups()
            if get_short_name(type_name) != stem:
                raise SystemExit(
                    f"{FATTN_MMA_QUANT_MANIFEST}: {type_name} has stem '{stem}', "
                    f"expected '{get_short_name(type_name)}'")
            (default_types if tier == "DEFAULT" else extra_types).append(type_name)

    if not default_types:
        raise SystemExit(f"{FATTN_MMA_QUANT_MANIFEST}: no DEFAULT tier entries found")

    return default_types, extra_types

SOURCE_FATTN_MMA_QUANT_START = """// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-mma-f16.cuh"

"""

SOURCE_FATTN_MMA_QUANT_CASE = ("DECL_FATTN_MMA_QUANT_CASE({type_k}, "
                               "{head_size}, {head_size}, {ncols1}, {ncols2});\n")

# The quantized-native MMA route covers every ordered K/V pair of the compiled
# types, but instantiates one kernel per K type rather than per pair: the V
# loader is chosen at runtime inside the kernel. So the inventory is linear in
# the number of native types, not quadratic, while coverage stays complete.

KVARN_MMA_HEAD_SIZES = [128, 256, 512]

SOURCE_FATTN_MMA_KVARN_START = """// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-mma-kvarn-case.cuh"

"""

SOURCE_FATTN_MMA_KVARN_CASE = "DECL_FATTN_MMA_KVARN_CASE({head_size}, {head_size}, {ncols1}, {ncols2});\n"

KVARN_DECODE_HEAD_SIZES = [128, 256, 512]
KVARN_DECODE_BITS = [2, 3, 4, 5, 6, 8]

SOURCE_FATTN_MMA_KVARN_DECODE = """// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-mma-kvarn-decode.cuh"{vec_include}

{cases}{vec_cases}
"""

TYPES_MMQ = [
    "GGML_TYPE_Q1_0",
    "GGML_TYPE_Q2_0",
    "GGML_TYPE_Q2_0S", "GGML_TYPE_Q2_1", "GGML_TYPE_Q3_0", "GGML_TYPE_Q3_1",
    "GGML_TYPE_Q4_0", "GGML_TYPE_Q4_1", "GGML_TYPE_Q5_0", "GGML_TYPE_Q5_1", "GGML_TYPE_Q6_0", "GGML_TYPE_Q6_1", "GGML_TYPE_Q8_0",
    "GGML_TYPE_Q2_K", "GGML_TYPE_Q3_K", "GGML_TYPE_Q4_K", "GGML_TYPE_Q5_K", "GGML_TYPE_Q6_K",
    "GGML_TYPE_IQ2_XXS", "GGML_TYPE_IQ2_XS", "GGML_TYPE_IQ2_S", "GGML_TYPE_IQ3_XXS", "GGML_TYPE_IQ3_S",
    "GGML_TYPE_IQ1_S", "GGML_TYPE_IQ4_NL", "GGML_TYPE_IQ4_XS", "GGML_TYPE_MXFP4", "GGML_TYPE_NVFP4"
]

SOURCE_MMQ = """// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../mmq.cuh"

DECL_MMQ_CASE({type});
"""

SOURCE_MMF = """// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../mmf.cuh"

DECL_MMF_CASE({type});
"""

def get_short_name(long_quant_name):
    return long_quant_name.replace("GGML_TYPE_", "").lower()


for filename in glob("*.cu"):
    os.remove(filename)

for head_size_kq in HEAD_SIZES_KQ:
    head_size_v = HEAD_SIZES_V_OVERRIDE.get(head_size_kq, head_size_kq)
    with open(f"fattn-tile-instance-dkq{head_size_kq}-dv{head_size_v}.cu", "w") as f:
        f.write(SOURCE_FATTN_TILE.format(head_size_kq=head_size_kq, head_size_v=head_size_v))

for type_k in TYPES_KV:
    for type_v in TYPES_KV:
        with open(f"fattn-vec-instance-{get_short_name(type_k)}-{get_short_name(type_v)}.cu", "w") as f:
            f.write(SOURCE_FATTN_VEC.format(type_k=type_k, type_v=type_v))

for type_k, type_v in EXTRA_FATTN_VEC_TYPES:
    with open(f"fattn-vec-instance-{get_short_name(type_k)}-{get_short_name(type_v)}.cu", "w") as f:
        f.write(SOURCE_FATTN_VEC.format(type_k=type_k, type_v=type_v))

for ncols in [8, 16, 32, 64]:
    for ncols2 in [1, 2, 4, 8, 16, 32]:
        if ncols2 > ncols:
            continue
        ncols1 = ncols // ncols2
        with open(f"fattn-mma-f16-instance-ncols1_{ncols1}-ncols2_{ncols2}.cu", "w") as f:
            f.write(SOURCE_FATTN_MMA_START)

            for head_size_kq in HEAD_SIZES_KQ:
                if head_size_kq == 40:
                    continue
                if head_size_kq == 72:
                    continue
                # Skip compilation of unused ncols2 values for niche head sizes:
                if head_size_kq == 192 and ncols2 not in (8, 16): # MiMo-V2.5
                    continue
                if head_size_kq == 320 and ncols2 != 32: # Mistral Small 4
                    continue
                if head_size_kq == 512 and ncols2 not in (2, 4, 8): # Gemma 4 (+ MTP)
                    continue
                if head_size_kq == 576 and ncols2 not in (4, 16, 32): # Deepseek, GLM 4.7 Flash
                    continue
                if head_size_kq not in (192, 320, 576) and ncols2 in (16, 32):
                    continue
                head_size_v = HEAD_SIZES_V_OVERRIDE.get(head_size_kq, head_size_kq)
                f.write(SOURCE_FATTN_MMA_CASE.format(ncols1=ncols1, ncols2=ncols2, head_size_kq=head_size_kq, head_size_v=head_size_v))

FATTN_MMA_QUANT_TYPES, FATTN_MMA_QUANT_TYPES_EXTRA = read_fattn_mma_quant_types()

for ncols in [8, 16, 32, 64]:
    for ncols2 in [1, 2, 4, 8]:
        if ncols2 > ncols:
            continue
        ncols1 = ncols // ncols2
        # One file per K type rather than one per column shape. The pair matrix
        # is 4.4x the cases the symmetric matrix had, and splitting by K keeps
        # each translation unit near its old size so the build still
        # parallelises instead of serialising behind a few huge files.
        for type_k in FATTN_MMA_QUANT_TYPES + FATTN_MMA_QUANT_TYPES_EXTRA:
            short_k = get_short_name(type_k)
            name = f"fattn-mma-quant-instance-{short_k}-ncols1_{ncols1}-ncols2_{ncols2}.cu"
            with open(name, "w") as f:
                f.write(SOURCE_FATTN_MMA_QUANT_START)
                extra_k = type_k in FATTN_MMA_QUANT_TYPES_EXTRA
                if extra_k:
                    f.write("#ifdef GGML_CUDA_FA_ALL_QUANTS\n")
                for head_size in FATTN_MMA_QUANT_HEAD_SIZES:
                    f.write(SOURCE_FATTN_MMA_QUANT_CASE.format(
                        type_k=type_k, head_size=head_size,
                        ncols1=ncols1, ncols2=ncols2))
                if extra_k:
                    f.write("#endif // GGML_CUDA_FA_ALL_QUANTS\n")

for ncols in [8, 16, 32, 64]:
    for ncols2 in [1, 2, 4, 8]:
        if ncols2 > ncols:
            continue
        ncols1 = ncols // ncols2
        with open(f"fattn-mma-kvarn-instance-ncols1_{ncols1}-ncols2_{ncols2}.cu", "w") as f:
            f.write(SOURCE_FATTN_MMA_KVARN_START)
            for head_size in KVARN_MMA_HEAD_SIZES:
                f.write(SOURCE_FATTN_MMA_KVARN_CASE.format(
                    head_size=head_size, ncols1=ncols1, ncols2=ncols2))

with open("fattn-mma-kvarn-instance-ncols1_16-ncols2_8.cu", "w") as f:
    f.write(SOURCE_FATTN_MMA_KVARN_START)
    f.write("#if !defined(GGML_USE_MUSA)\n")
    for head_size in [128, 256]:
        f.write(SOURCE_FATTN_MMA_KVARN_CASE.format(
            head_size=head_size, ncols1=16, ncols2=8))
        f.write(
            "template bool ggml_cuda_fattn_kvarn_wide_mma_supported<"
            f"{head_size}, {head_size}, 16, 8>(ggml_backend_cuda_context &, const ggml_tensor *);\n")
    f.write("#endif\n")

for bits_k in KVARN_DECODE_BITS:
    for bits_v in KVARN_DECODE_BITS:
        cases = "\n".join(
            f"DECL_FATTN_KVARN_DECODE_CASE({head_size}, {bits_k}, {bits_v});"
            for head_size in KVARN_DECODE_HEAD_SIZES)
        # Every KVarN bit pair gets the D256 low-parallelism vec instance; D512 vec is
        # intentionally excluded (it regressed deep-context global layers).
        vec_include = '\n#include "../fattn-kvarn-vec.cuh"'
        vec_cases = "\n" + "\n".join(
            f"DECL_FATTN_KVARN_VEC_CASE({head_size}, {bits_k}, {bits_v});"
            for head_size in KVARN_DECODE_HEAD_SIZES if head_size == 256)
        with open(f"fattn-mma-kvarn-decode-instance-k{bits_k}-v{bits_v}.cu", "w") as f:
            f.write(SOURCE_FATTN_MMA_KVARN_DECODE.format(
                cases=cases, vec_include=vec_include, vec_cases=vec_cases))

for type in TYPES_MMQ:
    with open(f"mmq-instance-{get_short_name(type)}.cu", "w") as f:
        f.write(SOURCE_MMQ.format(type=type))

for type in range(1, 17):
    with open(f"mmf-instance-ncols_{type}.cu", "w") as f:
        f.write(SOURCE_MMF.format(type=type))
